porygon/banco/data.sql
porygon/banco/schema.sql

Fiz os testes no insomnia e verifiquei no MySQL se populou o banco, ambos os testes deram certo

chore (#5): atualiza tabela usuario e cria scripts para cada cargo

---

porygon/banco/data.sql
porygon/banco/schema.sql

feat (#16): Cria tabela areas agricolas e exemplo para o banco

---

porygon/src/main/java/fatec/porygon/repository/AreaAgricolaRepository.java

feat (#17): criar repository para entidade area agricola

---

porygon/src/main/java/fatec/porygon/entity/CargoPermissao.java

(#29)
Correção da entidade CargoPermissao ao adicionar indicação de chave composta (@EmbeddedId)

fix(#29):  Correção mapeamento CargoPermissao

---

porygon/src/main/java/fatec/porygon/controller/UsuarioController.java
porygon/src/main/java/fatec/porygon/service/UsuarioService.java
porygon/src/main/resources/application.properties

#8 
Feito o CRUD:
POST /usuarios → Criar usuário
GET /usuarios → Listar usuários
GET /usuarios/{id} → Buscar usuário por ID
PUT /usuarios/{id} → Atualizar usuário
DELETE /usuarios/{id} → Remover usuário
Para testes no Postman:
POST /usuarios: http://localhost:8080/usuarios
{
"nome": "teste1",
"senha": "123456",
"email": "teste1@exemplo.com",
"cargoId": 3
}
GET /usuarios: http://localhost:8080/usuarios
Ao clicar em Send, verá os usuários.
GET /usuarios/{id}: http://localhost:8080/usuarios/1
Vai ver somente o usuario com ID 1
PUT /usuarios/{id}:http://localhost:8080/usuarios/1
{
"nome": "atualizado",
"senha": "teste1",
"email": "admin@visiona.com",
"cargoId": 3
}
DELETE /usuarios/{id}: http://localhost:8080/usuarios/1

feat(#8): Criar o Controller/Service para crud de Usuario

---

porygon/src/main/java/fatec/porygon/controller/AreaAgricolaController.java
porygon/src/main/java/fatec/porygon/entity/AreaAgricola.java
porygon/src/main/java/fatec/porygon/enums/StatusArea.java
porygon/src/main/java/fatec/porygon/service/AreaAgricolaService.java

feat(#18): crud area agricola

---

porygon/pom.xml
porygon/src/main/java/fatec/porygon/config/JwtConfig.java
porygon/src/main/java/fatec/porygon/config/SecurityConfig.java
porygon/src/main/java/fatec/porygon/controller/CargoPermissaoController.java
porygon/src/main/java/fatec/porygon/controller/LogController.java
porygon/src/main/java/fatec/porygon/controller/PermissaoController.java
porygon/src/main/java/fatec/porygon/controller/UsuarioController.java
porygon/src/main/java/fatec/porygon/dto/CargoPermissaoDto.java
porygon/src/main/java/fatec/porygon/dto/LogDto.java
porygon/src/main/java/fatec/porygon/dto/PermissaoDto.java
porygon/src/main/java/fatec/porygon/entity/CargoPermissao.java
porygon/src/main/java/fatec/porygon/entity/CargoPermissaoId.java
porygon/src/main/java/fatec/porygon/repository/CargoPermissaoRepository.java
porygon/src/main/java/fatec/porygon/repository/LogRepository.java
porygon/src/main/java/fatec/porygon/repository/PermissaoRepository.java
porygon/src/main/java/fatec/porygon/service/CargoPermissaoService.java
porygon/src/main/java/fatec/porygon/service/LogService.java
porygon/src/main/java/fatec/porygon/service/PermissaoService.java

Revert "feat(#9): Autenticar login do usuário com JWT"

---

porygon/src/main/java/fatec/porygon/controller/AreaAgricolaController.java
porygon/src/main/java/fatec/porygon/service/AutenticacaoService.java

feat(#35): adição de configurações de usuarios no post de areas agricolas

---

banco/data.sql
banco/schema.sql
src/main/java/fatec/porygon/config/JwtConfig.java
src/main/java/fatec/porygon/config/SecurityConfig.java
src/main/java/fatec/porygon/controller/AreaAgricolaController.java
src/main/java/fatec/porygon/dto/AreaAgricolaDto.java
src/main/java/fatec/porygon/dto/CargoDto.java
src/main/java/fatec/porygon/dto/CargoPermissaoDto.java
src/main/java/fatec/porygon/dto/LogDto.java
src/main/java/fatec/porygon/dto/PermissaoDto.java
src/main/java/fatec/porygon/dto/TalhaoDto.java
src/main/java/fatec/porygon/dto/UsuarioDto.java
src/main/java/fatec/porygon/entity/AreaAgricola.java
src/main/java/fatec/porygon/entity/Cargo.java
src/main/java/fatec/porygon/entity/CargoPermissao.java
src/main/java/fatec/porygon/entity/CargoPermissaoId.java
src/main/java/fatec/porygon/entity/Cidade.java
src/main/java/fatec/porygon/entity/Cultura.java
src/main/java/fatec/porygon/entity/Log.java
src/main/java/fatec/porygon/entity/Permissao.java
src/main/java/fatec/porygon/entity/Safra.java
src/main/java/fatec/porygon/entity/Talhao.java
src/main/java/fatec/porygon/entity/TipoSolo.java
src/main/java/fatec/porygon/entity/Usuario.java
src/main/java/fatec/porygon/service/AutenticacaoService.java
src/main/java/fatec/porygon/service/LogService.java
src/main/java/fatec/porygon/service/UsuarioService.java

Precisa dropar o banco e rodar novamente para testar , pois mudamos as tabelas

feat(#58): refatorar o back para padronizar a nomenclatura 

---

src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/entity/Safra.java
src/main/java/fatec/porygon/entity/Usuario.java
src/main/java/fatec/porygon/repository/SafraRepository.java
src/main/java/fatec/porygon/service/SafraService.java

#52 
---
1. **Método:** `PUT`
2. **URL:**  
```
http://localhost:8080/safras/1/associar-analista/3
```
3. **Body:**  
Nenhum body é necessário, pois o ID da safra e do analista são passados via URL.
---

feat(#52): preparar backend para associacao de safra com analista usuario analista

---

src/main/java/fatec/porygon/controller/AreaAgricolaController.java
src/main/java/fatec/porygon/dto/AreaAgricolaSimplificadaDto.java
src/main/java/fatec/porygon/dto/FazendaDetalhadaDto.java
src/main/java/fatec/porygon/dto/SafraFazendaDetalhadaDTO.java
src/main/java/fatec/porygon/dto/TalhaoFazendaDetalhadaDTO.java
src/main/java/fatec/porygon/entity/Safra.java
src/main/java/fatec/porygon/enums/StatusSafra.java
src/main/java/fatec/porygon/repository/TalhaoRepository.java
src/main/java/fatec/porygon/service/FazendaDetalhadaService.java

feat(#51): adicionado endpoint de fazenda detalhada

---

banco/data.sql
src/main/java/fatec/porygon/controller/TalhaoController.java
src/main/java/fatec/porygon/dto/TalhaoPendenteDto.java
src/main/java/fatec/porygon/entity/Safra.java
src/main/java/fatec/porygon/enums/StatusSafra.java
src/main/java/fatec/porygon/repository/TalhaoRepository.java
src/main/java/fatec/porygon/service/TalhaoService.java
src/main/resources/application.properties

feat(#53): Criar endpoint para listagem de talhões pendentes e sem analista atribuído

---

pom.xml
src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/controller/TalhaoController.java
src/main/java/fatec/porygon/dto/AreaAgricolaSimplificadaDto.java
src/main/java/fatec/porygon/dto/FazendaDetalhadaDto.java
src/main/java/fatec/porygon/dto/SafraDto.java
src/main/java/fatec/porygon/dto/SafraFazendaDetalhadaDTO.java
src/main/java/fatec/porygon/dto/TalhaoDto.java
src/main/java/fatec/porygon/dto/TalhaoFazendaDetalhadaDTO.java
src/main/java/fatec/porygon/entity/Safra.java
src/main/java/fatec/porygon/entity/Talhao.java
src/main/java/fatec/porygon/entity/TipoSolo.java
src/main/java/fatec/porygon/repository/CulturaRepository.java
src/main/java/fatec/porygon/repository/SafraRepository.java
src/main/java/fatec/porygon/repository/TalhaoRepository.java
src/main/java/fatec/porygon/repository/TipoSoloRepository.java
src/main/java/fatec/porygon/service/AreaAgricolaService.java
src/main/java/fatec/porygon/service/CulturaService.java
src/main/java/fatec/porygon/service/FazendaDetalhadaService.java
src/main/java/fatec/porygon/service/SafraService.java
src/main/java/fatec/porygon/service/TalhaoService.java
src/main/java/fatec/porygon/service/TipoSoloService.java

#47 
**Método:** `POST`  
**URL:** `http://localhost:8080/talhoes`
**Body (JSON):**  
```json
{
"area": 25.5,
"tipoSoloNome": "Teste",
"areaAgricola": 1,
"culturaNome": "Soja",
"ano": 2023,
"status": "Pendente",
"arquivoDaninha": "{\"type\": \"Polygon\", \"coordinates\": [[[10, 10], [20, 10], [20, 20], [10, 20], [10, 10]]]}",
"arquivoFinalDaninha": "{\"type\": \"Polygon\", \"coordinates\": [[[11, 11], [21, 11], [21, 21], [11, 21], [11, 11]]]}"
}
```
**Método:** `PUT`  
**URL:** `http://localhost:8080/talhoes/{id}`
**Body (JSON):**  
```json
{
"area": 25.5,
"tipoSoloNome": "Teste",
"areaAgricola": 1,
"culturaNome": "Soja",
"ano": 2023,
"status": "Pendente",
"arquivoDaninha": "{\"type\": \"Polygon\", \"coordinates\": [[[10, 10], [20, 10], [20, 20], [10, 20], [10, 10]]]}", …
```

feat(#47): Criar o repository controller e service para safra tiposolo cultura talhao

---

src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/dto/TalhaoResumoDto.java
src/main/java/fatec/porygon/repository/SafraRepository.java
src/main/java/fatec/porygon/service/SafraService.java

Método: GET
http://localhost:8080/api/talhoes/usuario/1
Substitua o 1 pelo ID do usuário que você quer testar.
3. Envie a requisição
Clique no botão "Send".
Se tudo estiver certo, o backend deve retornar um JSON semelhante a isso:
json
Copiar
Editar
{
"atribuidos": [
{
"idTalhao": 10,
"nomeFazenda": "Fazenda Esperança",
"idSafra": 15,
"nomeCultura": "Soja"
}
],
"aprovados": [
{
"idTalhao": 11,
"nomeFazenda": "Fazenda Aurora",
"idSafra": 18,
"nomeCultura": "Milho"
}
]
}

feat(#76): criado dto de resumo do talhao e duas listas de atribuido e aprovados

---

src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/dto/AtualizarSafraRequestDto.java
src/main/java/fatec/porygon/service/SafraService.java
src/main/java/fatec/porygon/service/TalhaoService.java

feat (#80): novo dto e endpoint para edicao do talhao

---

src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/controller/TalhaoController.java
src/main/java/fatec/porygon/dto/TalhaoPendenteDto.java
src/main/java/fatec/porygon/service/SafraService.java
src/main/java/fatec/porygon/service/TalhaoService.java

#88 
GET
http://localhost:8080/safras/pendentes

feat(#88):  adiciona metodo para listar safras pendentes e atualiza o TalhaopendenteDto

---

src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/dto/TalhaoResumoDto.java
src/main/java/fatec/porygon/repository/SafraRepository.java
src/main/java/fatec/porygon/service/SafraService.java

#91 
GET 
http://localhost:8080/safras/api/talhoes/usuario/id do usuario

feat(#91): adiciona o ano para as informações do TalhaoResumoDto

---

src/main/java/fatec/porygon/controller/RelatorioController.java
src/main/java/fatec/porygon/dto/RelatorioProdutividadeDto.java
src/main/java/fatec/porygon/service/RelatorioService.java

#94 
Para teste pode utilizar esses endpoint, estão com dados mockados, já que a task de service irá implelementar os dados.
http://localhost:8080/relatorios/status
http://localhost:8080/relatorios/analistas
http://localhost:8080/relatorios/produtividade

feat(#94): criar ControllerService e dados mockados no service utilizando os Dtos

---

src/main/java/fatec/porygon/service/TalhaoService.java

fix(#103): trazendo produtividade ano para os talhoes

---

src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/dto/SafraGeoJsonDto.java
src/main/java/fatec/porygon/service/SafraService.java

GET  http://localhost:8080/safras/{idSafra}/vetor
Vai retornar um mult fprm-data com cabeçãlho e os arquivos GeoJson

feat(#109): Criar endpoint para consulta de arquivos geojson por safra

---

src/main/java/fatec/porygon/repository/SafraRepository.java

fix(#114): corrigindo query de listagem por analista

---

src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/service/SafraService.java

no método salvar a edição modifiquei para ArquivoFinalErvaDaninha que é a versão intermediária em ves do arquivo original.
#122

fix(#122): salvar fase intermediaria no arquivofinaldaninha durante salvaredicaosafra

---

src/main/java/fatec/porygon/controller/TalhaoController.java
src/main/java/fatec/porygon/service/TalhaoService.java
src/main/resources/application.properties

#116 
Endpoint para teste: "http:localhost:8080/talhoes"

feat(#116): listagem baseada em safra

---

banco/data.sql
src/main/java/fatec/porygon/config/SecurityConfig.java
src/main/java/fatec/porygon/config/TomcatConfig.java
src/main/java/fatec/porygon/controller/AreaAgricolaController.java
src/main/java/fatec/porygon/controller/CargoPermissaoController.java
src/main/java/fatec/porygon/controller/CidadeController.java
src/main/java/fatec/porygon/controller/LogController.java
src/main/java/fatec/porygon/controller/PermissaoController.java
src/main/java/fatec/porygon/controller/RelatorioController.java
src/main/java/fatec/porygon/controller/SafraController.java
src/main/java/fatec/porygon/controller/TalhaoController.java
src/main/java/fatec/porygon/controller/UsuarioController.java
src/main/java/fatec/porygon/dto/CadastroAreaAgricolaDto.java
src/main/java/fatec/porygon/dto/SafraRelatorioDto.java
src/main/java/fatec/porygon/entity/Safra.java
src/main/java/fatec/porygon/service/AreaAgricolaService.java
src/main/java/fatec/porygon/service/CargoPermissaoService.java
src/main/java/fatec/porygon/service/CidadeService.java
src/main/java/fatec/porygon/service/FazendaDetalhadaService.java
src/main/java/fatec/porygon/service/LogService.java
src/main/java/fatec/porygon/service/PermissaoService.java
src/main/java/fatec/porygon/service/RelatorioService.java
src/main/java/fatec/porygon/service/SafraService.java
src/main/java/fatec/porygon/service/TalhaoService.java
src/main/java/fatec/porygon/service/UsuarioService.java
src/main/java/fatec/porygon/utils/ConvertGeoJsonUtils.java

feat(#117): efatoracao tratamento de erros nos endpoints

---

src/main/java/fatec/porygon/controller/TalhaoController.java
src/main/java/fatec/porygon/service/TalhaoService.java

fix(#127) bug atualiza talhao
